import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'package:random_reminder/screens/auth_screen.dart';
import 'package:random_reminder/screens/home_screen.dart';
import 'package:random_reminder/utilities/message_box.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final GlobalKey<MessageBoxState> messageBoxKey = GlobalKey<MessageBoxState>();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Random Reminders',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
        fontFamily: 'Inter', // Assuming 'Inter' font is available or added
      ),
      home: Stack(
        children: [
          StreamBuilder<User?>(
            stream: FirebaseAuth.instance.authStateChanges(),
            builder: (context, snapshot) {
              if (snapshot.connectionState == ConnectionState.waiting) {
                return const Scaffold(
                  body: Center(child: CircularProgressIndicator()),
                );
              }
              if (snapshot.hasData && snapshot.data != null) {
                // User is logged in, directly go to HomeScreen
                return HomeScreen(
                  userId: snapshot.data!.uid,
                  userEmail: snapshot.data!.email,
                  showMessage: (msg, type) =>
                      messageBoxKey.currentState?.showMessage(msg, type),
                );
              } else {
                // User is not logged in, show authentication screen
                return AuthScreen(
                  auth: FirebaseAuth.instance,
                  showMessage: (msg, type) =>
                      messageBoxKey.currentState?.showMessage(msg, type),
                );
              }
            },
          ),
          MessageBox(key: messageBoxKey),
        ],
      ),
    );
  }
}
